micronaut:
  server:
    port: 8085
    context-path: /api
  application:
    name: coroutinesBlog
netty:
  default:
    allocator:
      max-order: 3
mongodb:
  uri: mongodb://root:password@localhost:27017/coroutinesblog?authSource=admin